version: "3.8"

services:
  tor-proxy:
    container_name: tor-proxy
    image: chenjia404/tor-proxy:latest
    ports:
      - "127.0.0.1:8118:8118/tcp"
      - "127.0.0.1:8853:8853/udp"
      - "127.0.0.1:9150:9150/tcp"
      - "9001:9001/tcp"
    restart: unless-stopped
